version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: banda-deploy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123123
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
  s3:
    image: bitnami/minio
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./storage/minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_SERVER_ACCESS_KEY: minio
      MINIO_SERVER_SECRET_KEY: minio123
      MINIO_DEFAULT_BUCKETS: 'bucket:public'
